---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install prerequisites
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
      - gnupg
      - python3-urllib3
      - python3-requests
    update_cache: yes
    state: present

- name: Create keyrings directory
  become: yes
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key (ASCII, no dearmor)
  become: yes
  shell: |
    sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    sudo chmod a+r /etc/apt/keyrings/docker.asc

- name: Add Docker repository using .sources file
  become: yes
  copy:
    dest: /etc/apt/sources.list.d/docker.sources
    content: |
      Types: deb
      URIs: https://download.docker.com/linux/ubuntu
      Suites: jammy
      Components: stable
      Signed-By: /etc/apt/keyrings/docker.asc

- name: Update apt cache
  become: yes
  apt:
    update_cache: yes

- name: Install Docker components
  become: yes
  apt:
    name:
      - containerd.io
      - docker-ce
      - docker-ce-cli
    state: present

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Enable and start Docker services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - docker
    - containerd

- name: Add user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes

- name: Download CNI plugins
  become: yes
  shell: |
    curl -L https://github.com/containernetworking/plugins/releases/download/v1.4.0/cni-plugins-linux-amd64-v1.4.0.tgz \
    -o /tmp/cni-plugins.tgz

- name: Create CNI bin directory
  file:
    path: /opt/cni/bin
    state: directory

- name: Extract CNI plugins
  unarchive:
    src: /tmp/cni-plugins.tgz
    dest: /opt/cni/bin
    remote_src: yes


- name: Ensure containerd configuration directory exists
  file:
    path: /etc/containerd
    state: directory

- name: Generate containerd default config if not exists
  become: yes
  shell: |
    
      mkdir -p /etc/containerd
      containerd config default > /etc/containerd/config.toml
    

- name: Set SystemdCgroup = true in containerd config
  shell: |
    sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
    systemctl daemon-reload
    systemctl restart containerd
  become: yes
  notify: Restart containerd
- name: Ensure containerd is running
  service:
    name: containerd
    state: started
    enabled: yes